CREATE TABLE LOCATION (
  ID INTEGER PRIMARY KEY ON CONFLICT ABORT AUTOINCREMENT,
  CITY VARCHAR (128),
  STATE VARCHAR (128)
);

CREATE TABLE EMPLOYEE (
  ID INTEGER CONSTRAINT EMP_PK PRIMARY KEY ON CONFLICT ABORT AUTOINCREMENT,
  FIRSTNAME VARCHAR (255),
  LASTNAME VARCHAR (255),
  DOB DATE,
  ROLE STRING (32) CONSTRAINT ROLE_NOT_NULL NOT NULL ON CONFLICT ABORT,
  LOC_ID INTEGER REFERENCES LOCATION (ID) ON DELETE CASCADE ON UPDATE CASCADE MATCH [FULL],
  WORK_EMAIL VARCHAR (128),
  MANAGER_ID INTEGER REFERENCES EMPLOYEE (ID)
);

CREATE TABLE CONFIGURATION (
  ID INTEGER PRIMARY KEY ON CONFLICT ABORT AUTOINCREMENT,
  NAME VARCHAR (255) NOT NULL,
  CREATION_TIME DATETIME DEFAULT SYSDATE,
  DESCRIPTION VARCHAR (512),
  OWNER INTEGER CONSTRAINT CONFIG_EMP_FK REFERENCES EMPLOYEE (ID) ON DELETE CASCADE ON UPDATE CASCADE MATCH [FULL]
);

CREATE TABLE LOT (
  ID INTEGER PRIMARY KEY ON CONFLICT ABORT AUTOINCREMENT,
  NAME VARCHAR (255) NOT NULL,
  MATERIAL_TYPE VARCHAR (32) CONSTRAINT CHECK_MATERIAL_TYPE CHECK (MATERIAL_TYPE IN ("PLASTIC", "METAL", "GLASS")),
  HEIGHT DECIMAL (4),
  DIAMETER DECIMAL (4),
  CONFIGURATION INTEGER CONSTRAINT LOT_CONFIG_FK REFERENCES CONFIGURATION (ID) ON DELETE CASCADE ON UPDATE CASCADE MATCH [FULL],
  LOC_ID INTEGER REFERENCES LOCATION (ID) ON DELETE CASCADE ON UPDATE CASCADE MATCH [FULL]
);

CREATE TABLE PART (
  ID INTEGER PRIMARY KEY ON CONFLICT ABORT AUTOINCREMENT,
  TEST_START_TIME DATETIME,
  TEST_END_TIME DATETIME,
  BUCKET INTEGER,
  LOT INTEGER CONSTRAINT PART_LOT_FK REFERENCES LOT (ID) ON DELETE CASCADE ON UPDATE CASCADE MATCH [FULL]
);

CREATE TABLE DEFECT (
  ID INTEGER PRIMARY KEY ON CONFLICT ABORT AUTOINCREMENT,
  TYPE VARCHAR (128) CONSTRAINT DEFECT_TYPE_CHECK CHECK (TYPE IN ("SCRATCH", "HOLE", "DIM_ERR")) NOT NULL
);

CREATE TABLE DEFECT_SCRATCH (
  DEFECT_ID INTEGER CONSTRAINT DEFECT_SCRATCH_FK REFERENCES DEFECT (ID) ON DELETE CASCADE ON UPDATE CASCADE MATCH [FULL],
  DEPTH DECIMAL (4),
  ASPECT_RATIO VARCHAR (128)
);

CREATE TABLE DEFECT_HOLE (
  DEFECT_ID INTEGER CONSTRAINT HOLE_DEFECT_FK REFERENCES DEFECT (ID) ON
DELETE CASCADE ON UPDATE CASCADE MATCH [FULL],
  DIAMETER DECIMAL (4),
  CIRCULAR_RATIO DECIMAL (1)
);

CREATE TABLE DEFECT_DIMENSION_ERROR (
  DEFECT_ID INTEGER CONSTRAINT DIM_DEFECT_FK REFERENCES DEFECT (ID) ON
DELETE CASCADE ON UPDATE
  SET
    DEFAULT MATCH [FULL],
    ACTUAL_DIAMETER DECIMAL (4),
    ACTUAL_HEIGHT DECIMAL (4)
);

CREATE TABLE PART_DEFECT (
  PART_ID CONSTRAINT PART_DEFECT_FK REFERENCES PART (ID) ON DELETE CASCADE ON UPDATE CASCADE MATCH [FULL],
  DEFECT_ID INTEGER CONSTRAINT DEFECT_PART_FK REFERENCES DEFECT (ID) ON
DELETE CASCADE ON UPDATE CASCADE MATCH [FULL],
  DEFECT_COUNT INTEGER,
  SEVERITY VARCHAR (128) CONSTRAINT SEVERITY_CHECK CHECK (
    SEVERITY IN ("CRITICAL", "HIGH", "MEDIUM", "LOW")
  )
);