DROP TABLE DEFECT_DIMENSION_ERROR;
DROP TABLE DEFECT_HOLE;
DROP TABLE DEFECT_SCRATCH;
DROP TABLE PART_DEFECT;
DROP TABLE DEFECT;
DROP TABLE PART;
DROP TABLE LOT;
DROP TABLE CONFIGURATION;
DROP TABLE EMPLOYEE;
DROP TABLE LOCATION;

CREATE TABLE LOCATION (
  ID INTEGER PRIMARY KEY ON CONFLICT ABORT AUTOINCREMENT,
  CITY VARCHAR (128),
  STATE VARCHAR (128)
);

CREATE TABLE EMPLOYEE (
  ID INTEGER CONSTRAINT EMP_PK PRIMARY KEY ON CONFLICT ABORT AUTOINCREMENT,
  FIRSTNAME VARCHAR (255),
  LASTNAME VARCHAR (255),
  DOB DATE,
  ROLE STRING (32) CONSTRAINT ROLE_NOT_NULL NOT NULL ON CONFLICT ABORT,
  LOC_ID INTEGER REFERENCES LOCATION (ID) ON DELETE CASCADE ON UPDATE CASCADE MATCH [FULL],
  WORK_EMAIL VARCHAR (128),
  MANAGER_ID INTEGER REFERENCES EMPLOYEE (ID)
);

CREATE TABLE CONFIGURATION (
  ID INTEGER PRIMARY KEY ON CONFLICT ABORT AUTOINCREMENT,
  NAME VARCHAR (255) NOT NULL,
  CREATION_TIME DATETIME DEFAULT SYSDATE,
  DESCRIPTION VARCHAR (512),
  OWNER INTEGER CONSTRAINT CONFIG_EMP_FK REFERENCES EMPLOYEE (ID) ON DELETE CASCADE ON UPDATE CASCADE MATCH [FULL]
);

CREATE TABLE LOT (
  ID INTEGER PRIMARY KEY ON CONFLICT ABORT AUTOINCREMENT,
  NAME VARCHAR (255) NOT NULL,
  MATERIAL_TYPE VARCHAR (32) CONSTRAINT CHECK_MATERIAL_TYPE CHECK (MATERIAL_TYPE IN ("PLASTIC", "METAL", "GLASS")),
  HEIGHT DECIMAL (4),
  DIAMETER DECIMAL (4),
  CONFIGURATION INTEGER CONSTRAINT LOT_CONFIG_FK REFERENCES CONFIGURATION (ID) ON DELETE CASCADE ON UPDATE CASCADE MATCH [FULL],
  ASSIGNEE INTEGER CONSTRAINT LOT_EOMPLOYEE_FK REFERENCES EMPLOYEE (ID) ON DELETE CASCADE ON UPDATE CASCADE MATCH [FULL],
  LOC_ID INTEGER REFERENCES LOCATION (ID) ON DELETE CASCADE ON UPDATE CASCADE MATCH [FULL]
);

CREATE TABLE PART (
  ID INTEGER PRIMARY KEY ON CONFLICT ABORT AUTOINCREMENT,
  TEST_START_TIME DATETIME,
  TEST_END_TIME DATETIME,
  BUCKET INTEGER,
  LOT INTEGER CONSTRAINT PART_LOT_FK REFERENCES LOT (ID) ON DELETE CASCADE ON UPDATE CASCADE MATCH [FULL]
);

CREATE TABLE DEFECT (
  ID INTEGER PRIMARY KEY ON CONFLICT ABORT AUTOINCREMENT,
  TYPE VARCHAR (128) CONSTRAINT DEFECT_TYPE_CHECK CHECK (TYPE IN ("SCRATCH", "HOLE", "DIM_ERR")) NOT NULL
);

CREATE TABLE DEFECT_SCRATCH (
  DEFECT_ID INTEGER CONSTRAINT DEFECT_SCRATCH_FK REFERENCES DEFECT (ID) ON DELETE CASCADE ON UPDATE CASCADE MATCH [FULL],
  DEPTH DECIMAL (4),
  ASPECT_RATIO VARCHAR (128)
);

CREATE TABLE DEFECT_HOLE (
  DEFECT_ID INTEGER CONSTRAINT HOLE_DEFECT_FK REFERENCES DEFECT (ID) ON
DELETE CASCADE ON UPDATE CASCADE MATCH [FULL],
  DIAMETER DECIMAL (4),
  CIRCULAR_RATIO DECIMAL (1)
);

CREATE TABLE DEFECT_DIMENSION_ERROR (
  DEFECT_ID INTEGER CONSTRAINT DIM_DEFECT_FK REFERENCES DEFECT (ID) ON
DELETE CASCADE ON UPDATE
  SET
    DEFAULT MATCH [FULL],
    ACTUAL_DIAMETER DECIMAL (4),
    ACTUAL_HEIGHT DECIMAL (4)
);

CREATE TABLE PART_DEFECT (
  PART_ID CONSTRAINT PART_DEFECT_FK REFERENCES PART (ID) ON DELETE CASCADE ON UPDATE CASCADE MATCH [FULL],
  DEFECT_ID INTEGER CONSTRAINT DEFECT_PART_FK REFERENCES DEFECT (ID) ON
DELETE CASCADE ON UPDATE CASCADE MATCH [FULL],
  DEFECT_COUNT INTEGER,
  SEVERITY VARCHAR (128) CONSTRAINT SEVERITY_CHECK CHECK (
    SEVERITY IN ("CRITICAL", "HIGH", "MEDIUM", "LOW")
  )
);


INSERT INTO LOCATION(CITY,STATE) VALUES("MUMBAI","MAHARASHTRA");
INSERT INTO LOCATION(CITY,STATE) VALUES("CHENNAI","TAMIL NADU");
INSERT INTO LOCATION(CITY,STATE) VALUES("BENGALURU","KARNATAKA");
INSERT INTO LOCATION(CITY,STATE) VALUES("KOLKATA","WEST BENGAL");
INSERT INTO LOCATION(CITY,STATE) VALUES("BHUBANESWAR","ODISHA");
INSERT INTO LOCATION(CITY,STATE) VALUES("BHOPAL","MADHYA PRADESH");
INSERT INTO LOCATION(CITY,STATE) VALUES("BIHAR","PATNA");
INSERT INTO LOCATION(CITY,STATE) VALUES("GANDHINAGAR","GUJURAT");
INSERT INTO LOCATION(CITY,STATE) VALUES("JAIPUR","RAJASTHAN");
INSERT INTO LOCATION(CITY,STATE) VALUES("IMPHAL","MANIPUR");


INSERT INTO EMPLOYEE(FIRSTNAME,LASTNAME,DOB,ROLE,LOC_ID,WORK_EMAIL) VALUES ("SUCHARITA","TRIPATHY","1990-07-06","CQE",2,"SUCHARITA.TRIPATHY@TEST.COM");
INSERT INTO EMPLOYEE(FIRSTNAME,LASTNAME,DOB,ROLE,LOC_ID,WORK_EMAIL) VALUES ("UJJWAL","KALRA","1990-07-05","CQE",3,"UJJWAL.KALRA@TEST.COM");
INSERT INTO EMPLOYEE(FIRSTNAME,LASTNAME,DOB,ROLE,LOC_ID,WORK_EMAIL) VALUES ("AKHIL","S","1990-07-05","PPDE",4,"AKHIL.S@TEST.COM");
INSERT INTO EMPLOYEE(FIRSTNAME,LASTNAME,DOB,ROLE,LOC_ID,WORK_EMAIL) VALUES ("SHRUTI","KATARE","1990-07-04","PPDE",5,"SHRUTI.KATARE@TEST.COM");
INSERT INTO EMPLOYEE(FIRSTNAME,LASTNAME,DOB,ROLE,LOC_ID,WORK_EMAIL) VALUES ("ANCHAL","GUPTA","1990-07-03","PPDE",6,"ANCHAL.GUPTA@TEST.COM");
INSERT INTO EMPLOYEE(FIRSTNAME,LASTNAME,DOB,ROLE,LOC_ID,WORK_EMAIL) VALUES ("MALAY","ROUTERLA","1990-07-02","PPDE",7,"MALAY.ROUTELA@TEST.COM");

UPDATE EMPLOYEE SET MANAGER_ID=2 WHERE ID IN (1,2,3,4,5,6);

INSERT INTO CONFIGURATION(NAME,CREATION_TIME,DESCRIPTION,OWNER) VALUES ("CONFIG1",DATETIME('NOW'),"DETAILED SPECIFICATION CAN BE FOUND AT HTTP://TEST.COM",1);
INSERT INTO CONFIGURATION(NAME,CREATION_TIME,DESCRIPTION,OWNER) VALUES ("CONFIG2",DATETIME('NOW'),"DETAILED SPECIFICATION CAN BE FOUND AT HTTP://TEST1.COM",2);
INSERT INTO CONFIGURATION(NAME,CREATION_TIME,DESCRIPTION,OWNER) VALUES ("CONFIG3",DATETIME('NOW'),"DETAILED SPECIFICATION CAN BE FOUND AT HTTP://TEST2.COM",3);

INSERT INTO LOT(NAME,MATERIAL_TYPE,HEIGHT,DIAMETER,CONFIGURATION,LOC_ID,ASSIGNEE) VALUES("TEST-LOT-1","METAL",20.6,7.3,1,2,3);
INSERT INTO LOT(NAME,MATERIAL_TYPE,HEIGHT,DIAMETER,CONFIGURATION,LOC_ID,ASSIGNEE) VALUES("TEST-LOT-2","GLASS",28.45,8.38,2,2,3);
INSERT INTO LOT(NAME,MATERIAL_TYPE,HEIGHT,DIAMETER,CONFIGURATION,LOC_ID,ASSIGNEE) VALUES("TEST-LOT-3","PLASTIC",30,7.3,3,2,6);

INSERT INTO PART(TEST_START_TIME,TEST_END_TIME,BUCKET,LOT) VALUES("2021-10-25 02:34:56","2021-10-25 04:50:50",0,1);
INSERT INTO PART(TEST_START_TIME,TEST_END_TIME,BUCKET,LOT) VALUES("2021-10-26 02:34:56","2021-10-26 04:50:50",0,1);
INSERT INTO PART(TEST_START_TIME,TEST_END_TIME,BUCKET,LOT) VALUES("2021-10-27 02:34:56","2021-10-27 04:50:50",0,1);
INSERT INTO PART(TEST_START_TIME,TEST_END_TIME,BUCKET,LOT) VALUES("2021-10-27 02:34:56","2021-10-27 04:50:50",0,1);
INSERT INTO PART(TEST_START_TIME,TEST_END_TIME,BUCKET,LOT) VALUES("2021-10-27 01:34:56","2021-10-27 03:50:50",0,1);
INSERT INTO PART(TEST_START_TIME,TEST_END_TIME,BUCKET,LOT) VALUES("2021-10-25 02:34:56","2021-10-25 04:50:50",0,1);
INSERT INTO PART(TEST_START_TIME,TEST_END_TIME,BUCKET,LOT) VALUES("2021-10-26 02:34:56","2021-10-26 04:50:50",0,1);
INSERT INTO PART(TEST_START_TIME,TEST_END_TIME,BUCKET,LOT) VALUES("2021-10-27 02:34:56","2021-10-27 04:50:50",0,1);
INSERT INTO PART(TEST_START_TIME,TEST_END_TIME,BUCKET,LOT) VALUES("2021-10-27 02:34:56","2021-10-27 04:50:50",0,1);
INSERT INTO PART(TEST_START_TIME,TEST_END_TIME,BUCKET,LOT) VALUES("2021-10-27 01:34:56","2021-10-27 03:50:50",0,1);

INSERT INTO DEFECT(TYPE) VALUES("SCRATCH");
INSERT INTO DEFECT(TYPE) VALUES("HOLE");
INSERT INTO DEFECT(TYPE) VALUES("DIM_ERR");

INSERT INTO DEFECT_HOLE(DEFECT_ID,DIAMETER,CIRCULAR_RATIO) VALUES(2,0.2,0.9);
INSERT INTO DEFECT_SCRATCH(DEFECT_ID,DEPTH,ASPECT_RATIO) VALUES(1,0.01,"16:9");
INSERT INTO DEFECT_DIMENSION_ERROR(DEFECT_ID,ACTUAL_DIAMETER,ACTUAL_HEIGHT) VALUES(3,30.9,7.4);

INSERT INTO PART_DEFECT(PART_ID,DEFECT_ID,DEFECT_COUNT,SEVERITY) VALUES(1,1,2,"LOW");
INSERT INTO PART_DEFECT(PART_ID,DEFECT_ID,DEFECT_COUNT,SEVERITY) VALUES(2,1,3,"LOW");
INSERT INTO PART_DEFECT(PART_ID,DEFECT_ID,DEFECT_COUNT,SEVERITY) VALUES(3,2,1,"LOW");
INSERT INTO PART_DEFECT(PART_ID,DEFECT_ID,DEFECT_COUNT,SEVERITY) VALUES(8,2,1,"LOW");
INSERT INTO PART_DEFECT(PART_ID,DEFECT_ID,DEFECT_COUNT,SEVERITY) VALUES(4,3,1,"HIGH");
INSERT INTO PART_DEFECT(PART_ID,DEFECT_ID,DEFECT_COUNT,SEVERITY) VALUES(5,1,2,"HIGH");
INSERT INTO PART_DEFECT(PART_ID,DEFECT_ID,DEFECT_COUNT,SEVERITY) VALUES(6,1,3,"HIGH");
INSERT INTO PART_DEFECT(PART_ID,DEFECT_ID,DEFECT_COUNT,SEVERITY) VALUES(7,2,1,"CRITICAL");

